name: Deploy Docsify Docs

on:
  push:
    branches: [ dev ]
    paths:
      - 'docs/**'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './docs'  # 指定您的 docsify 文档目录
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3